### ISSUE TITLE
Relación Review y Dish

### ISSUE THREAD

**Issue by fringlesinthestreet** [desarrollo-kissthecook/backend#46]
En la query de Dish, falta la conexión con reviews. 

Hasta ahora no puedo listar todos los reviews de un chef :(.

**Comment by iqacevedo** [comment]
Hola ya las deje conectadas en #51:

Por ejemplo, cuando se pide la query dishes que devuelve todos los platos, los reviews se obtendrán asi:
```js
{
  dishes{
    id
    dishReviews{
      comment
      ranking
      id
    }
  }
}
```

**Comment by iqacevedo** [comment]
@fringlesinthestreet avisame cuando lo veas

**Comment by fringlesinthestreet** [comment]
Funciona :tada:
